name: Deploy Rust Lambda Function

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Setup Rust
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     profile: minimal
      #     override: true

      - name: Install build dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y build-essential
          sudo curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y

      #    cargo install cargo-lambda

      - name: Install Zig
        run: |
          sudo wget https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.184+bf588f67d.tar.xz
          sudo tar -xf zig-linux-x86_64-0.14.0-dev.184+bf588f67d.tar.xz
          sudo mv zig-linux-x86_64-0.14.0-dev.184+bf588f67d /usr/local/zig
        shell: bash

      - name: Update PATH for Zig
        run: echo "/usr/local/zig" >> $GITHUB_PATH

      - name: Verify Zig Installation
        run: zig version
      #    cargo lambda build --release --target x86_64-unknown-linux-musl

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
      #     role-session-name: DeployLambda
      #     aws-region: eu-north-1

      # - name: Install CDK
      #   run: |
      #     npm install -g typescript
      #     npm install -g ts-node
      #     sudo npm install -g aws-cdk

      # - name: CDK Deploy
      #   run: |
      #     cd deploy
      #     yarn install
      #     yarn build
      #     yarn cdk deploy --parameters LambdaArchitecture=arm64 --require-approval never